name: glib
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  args: ^2.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  directed_graph: ^0.4.3
  girepository:
    git: https://github.com/HrX03/girepository.dart
  lints: ^4.0.0
  path: ^1.9.0
  test: ^1.24.0
